import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { migrate } from 'drizzle-orm/neon-http/migrator';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { storage } from './storage';

export async function setupDatabase() {
  try {
    if (!process.env.DATABASE_URL) {
      console.error('DATABASE_URL environment variable is not set');
      return;
    }

    console.log('Starting database setup...');

    const sql = neon(process.env.DATABASE_URL);
    const db = drizzle(sql);
    const migrationsFolder = resolve(dirname(fileURLToPath(import.meta.url)), '../migrations');

    // Run SQL migrations generated by drizzle-kit
    try {
      console.log('Applying database migrations...');
      await migrate(db, { migrationsFolder });
      console.log('Database migrations applied successfully!');
    } catch (migrationError) {
      console.error('Error applying database migrations:', migrationError);
      throw migrationError;
    }

    // Initialize demo data after migrations are applied
    try {
      if (process.env.DATABASE_URL && storage.constructor.name === 'PostgreSQLStorage') {
        const pgStorage = storage as any;
        if (typeof pgStorage.initialize === 'function') {
          console.log('Initializing demo data...');
          await pgStorage.initialize();
          console.log('Demo data initialization complete.');
        }
      }
    } catch (initError) {
      console.error('Error initializing database data:',
        initError instanceof Error ? initError.message : String(initError));
    }
    
  } catch (error) {
    console.error('Error setting up the database:',
      error instanceof Error ? error.message : String(error));
  }
}